worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: true

server-port: 8080

dbconnection: 'postgresql://testsuite@localhost:15433/url_shortener_url_shortener'

base_url: 'http://base.url'
len: 5
